import Navbar from '../components/navbar/Navbar';
import './global.css';
import ReactQueryProvider from '../providers/reactQuery-provider';
import MaxWidthContainer from '../components/layout/MaxWidthContainer';

export const metadata = {
  title: 'Welcome to frontend',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ReactQueryProvider>
          <Navbar />
          <MaxWidthContainer>
            {children}
          </MaxWidthContainer>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
