
import './global.css';
import Header from '../components/header/Header';
import './global.css';
import ReactQueryProvider from '../providers/reactQuery-provider';
import MaxWidthContainer from '../components/layout/MaxWidthContainer';
import AuthContextProvider from '../contexts/AuthContext';

export const metadata = {
  title: 'Welcome to frontend',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ReactQueryProvider>
          <AuthContextProvider>
            <Header />
            <MaxWidthContainer>
              {children}
            </MaxWidthContainer>
          </AuthContextProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
