yarnPath: .yarn/releases/yarn-4.10.3.cjs
nodeLinker: node-modules

# 네이티브 모듈 빌드 최적화
enableGlobalCache: false
enableMirror: false

# Alpine Linux 환경에서 네이티브 모듈 빌드 지원
enableProgressBars: true
enableTelemetry: false

# 패키지 설치 최적화
httpTimeout: 60000
httpRetry: 3