# PostgreSQL만 실행하는 Docker Compose 파일

services:
  # PostgreSQL 데이터베이스만 실행
  postgres:
    image: postgres:18-alpine
    restart: unless-stopped
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./backend/postgres-data:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: sangmoon
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sangmoon
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sangmoon"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_dev_data:
    driver: local

networks:
  default:
    name: shopping-mall-db-network
